collections:
  Spectacles:
    plex_all: true
    filters:
      - filepath.regex: '/data/movies/_spectacles/'

  Émissions:
    plex_all: true
    filters:
      - filepath.regex: '/data/movies/_broadcasts/'

  Concerts:
    plex_all: true
    filters:
      - filepath.regex: '/data/movies/_concerts/'
