######################################################
#              Trakt Dynamic Collections             #
######################################################

templates:
  trakt:
    trakt_list_details: <<trakt_user_lists>>
  trakt_liked:
    trakt_list_details: <<value>>

dynamic_collections:
  #Create collections based on the Trakt lists associated with the authenticated user.
  Trakt List Collections:
    template: trakt
    type: trakt_user_lists
    data: me
    exclude:
      - Radarr
      - Sonarr
      - Favorites
      #- Watchlist
      
  #Create collections based on the liked Trakt lists.
  Trakt Liked Lists:
    template: trakt_liked
    type: trakt_liked_lists
